##
## EPITECH PROJECT, 2022
## my lib
## File description:
## Makefile
##

TODO	=	all
SUBDIRS := $(wildcard */.)

all: TODO	=	all
all: $(SUBDIRS)

clean: TODO	=	clean
clean: $(SUBDIRS)

fclean: TODO	=	fclean
fclean: $(SUBDIRS)

$(SUBDIRS):
		$(MAKE) -C $@ $(TODO)

.PHONY: all $(SUBDIRS)
